### ISSUE TITLE
Number of CPU cores?

### ISSUE THREAD

**Issue by esidegallery** [tuarua/WindowsHelperANE#1]
Hi tuarua,
How possible would it be to add a method to retrieve the number of CPU cores on the system? Would be really handy to determine how many simultaneous workers can be run. Thanks.

**Comment by tuarua** [comment]
Is very possible
https://stackoverflow.com/questions/1542213/how-to-find-the-number-of-cpu-cores-via-net-c

**Comment by tuarua** [comment]
This has now been added - getNumLogicalProcessors()
Will give you the number of threads you can create

**Comment by esidegallery** [comment]
Amazing! Thank you for doing this tuarua.

**Comment by tuarua** [comment]
np, was a quick addition and comes in handy for myself
