### ISSUE TITLE
startAtLogin for Captive Runtime Applications

### ISSUE THREAD

**Issue by esidegallery** [tuarua/WindowsHelperANE#6]
Hey @tuarua, I'm experiencing strange behaviour when trying to set startAtLogin from a captive runtime. The isSupported property is true, but when I try to change it, it seems to just hang. Even if I move the app to Program Files, the problem persists. Is this something you have had experience with? If setting this flag from a captive runtime is impossible, how difficult would it be to add startAtLogin functionality to this ANE? I can contribute financially to its development, if you let me know how much. Many thanks!

**Comment by tuarua** [comment]
I can't even read the property.
`NativeApplication.nativeApplication.startAtLogin`
`Error: Error #2014: Feature is not available at this time.`

I'll take a look. I think it needs to set a registry key
SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run

**Comment by esidegallery** [comment]
I didn't actually try reading the property, but in any case the
supportsStartAtLogin is incorrectly returning true. Thank @tuarua, that
would be fantastic.

**Comment by tuarua** [comment]
have added startAtLogin
eg
`windowsHelper.startAtLogin("MyAirApp", true);`

Pass app name. This adds the exe to registry under SOFTWARE\Microsoft\Windows\CurrentVersion\Run

**Comment by esidegallery** [comment]
Amazing @tuarua! I've been on holiday, but will test today...
